apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2sar-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e2sar-sender
  template:
    metadata:
      labels:
        app: e2sar-sender
    spec:
      containers:
      - name: e2sar-sender
        image: e2sar-container:latest
        imagePullPolicy: Never
        command: ["/app/entrypoint-sender.sh"]
        env:
        - name: URI
          value: "ejfat://useless@10.10.10.10:1234/lb/1?data=$(RECEIVER_IP)&sync=192.168.77.7:1234"
        - name: MTU
          value: "9000"
        - name: RATE
          value: "10"
        - name: LENGTH
          value: "1000000"
        - name: NUM_EVENTS
          value: "10000"
        - name: BUF_SIZE
          value: "314572800"
        - name: DIRECT_MODE
          value: "true"
        - name: RECEIVER_IP
          valueFrom:
            configMapKeyRef:
              name: e2sar-config
              key: receiver_ip
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi" 