apiVersion: v1
kind: Pod
metadata:
  name: frontend-test
  labels:
    app: frontend
    tier: web
spec:
  containers:
  - name: curl
    image: curlimages/curl:latest
    command: ["/bin/sh", "-c"]
    args:
    - |
      while true; do
        echo "Testing frontend to backend communication..."
        curl -v backend:8080/api/test
        echo -e "\nSleeping for 5 seconds..."
        sleep 5
      done
---
apiVersion: v1
kind: Pod
metadata:
  name: backend-test
  labels:
    app: backend
    tier: api
spec:
  containers:
  - name: redis-cli
    image: redis:6.2
    command: ["/bin/sh", "-c"]
    args:
    - |
      while true; do
        echo "Testing backend to database communication..."
        redis-cli -h database ping
        echo -e "\nSleeping for 5 seconds..."
        sleep 5
      done 