apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: kube-system
data:
  agent-not-ready-taint-key: node.cilium.io/agent-not-ready
  bpf-root: /sys/fs/bpf
  cgroup-root: /run/cilium/cgroupv2
  cluster-name: default
  cluster-id: "0"
  debug: "false"
  enable-ipv4: "true"
  enable-ipv6: "false"
  enable-k8s-networkpolicy: "true"
  enable-l7-proxy: "true"
  enable-policy: "default"
  enable-bpf-masquerade: "true"
  enable-ipv4-masquerade: "true"
  ipam: kubernetes
  kube-proxy-replacement: "strict"
  tunnel-protocol: "vxlan"
  routing-mode: "tunnel"
  enable-endpoint-routes: "false"
  enable-auto-protect-node-port-range: "true"
  enable-health-checking: "true"
  enable-metrics: "true"
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  k8sServiceHost: cilium-cluster-control-plane
  k8sServicePort: 6443
  hostServices:
    enabled: true
  externalIPs:
    enabled: true
  nodePort:
    enabled: true
  hostPort:
    enabled: true
  image:
    pullPolicy: IfNotPresent
  hubble:
    enabled: true
    metrics:
      enabled:
        - dns:query;ignoreAAAA
        - drop
        - tcp
        - flow
        - icmp
        - http
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
    port: 9090
  metrics:
    enabled:
      - api
      - controller
      - datapath
      - drop
      - endpoint
      - errors-warnings
      - forwarding
      - identity
      - ipcache
      - k8s-client
      - kubernetes-events
      - nodes
      - policy
      - process
      - service
      - signal
      - workqueue 