version: '3'

services:
  sender:
    image: e2sar-container
    network_mode: host
    container_name: e2sar-sender
    entrypoint: /app/entrypoint-sender.sh
    environment:
      - URI=ejfats://token@${LB_IP:-localhost}:18008/
      - MTU=${MTU:-9000}
      - RATE=${RATE:-10}
      - LENGTH=${LENGTH:-1000000}
      - NUM_EVENTS=${NUM_EVENTS:-10000}
      - BUF_SIZE=${BUF_SIZE:-314572800}
      - IP=${SENDER_IP:-localhost}

  receiver:
    image: e2sar-container
    network_mode: host
    container_name: e2sar-receiver
    entrypoint: /app/entrypoint-receiver.sh
    environment:
      - URI=ejfats://token@${LB_IP:-localhost}:18008/
      - DURATION=${DURATION:-30}
      - BUF_SIZE=${BUF_SIZE:-314572800}
      - IP=${RECEIVER_IP:-localhost}
      - PORT=${PORT:-19522}
      - THREADS=${THREADS:-1}